# Generated by Django 5.2.14 on 2026-05-20 19:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_type', models.CharField(choices=[('gun', 'Gun'), ('knife', 'Knife'), ('sword', 'Sword')], max_length=20)),
                ('detection_type', models.CharField(choices=[('weapon', 'Weapon Only'), ('armed', 'Armed Person')], default='weapon', max_length=20)),
                ('confidence', models.FloatField()),
                ('camera_source', models.CharField(default='Webcam 01', max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('frame_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('info', 'Info'), ('warn', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_source', models.CharField(default='webcam', max_length=20)),
                ('iphone_url', models.CharField(default='http://192.168.0.102:8081/video', max_length=200)),
                ('resolution', models.CharField(default='320x240', max_length=20)),
                ('confidence', models.FloatField(default=50)),
                ('frame_skip', models.IntegerField(default=3)),
                ('detect_gun', models.BooleanField(default=True)),
                ('detect_knife', models.BooleanField(default=True)),
                ('detect_sword', models.BooleanField(default=True)),
                ('armed_person', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'System Settings',
            },
        ),
    ]
